import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import "./reset.css";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import Script from "next/script";
import AuthProvider from "@/provider/AuthProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome to Hotel App Reservation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <Script
          src="https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=6kilhlwyk3"
          strategy="beforeInteractive"
          />
      </head>
      <AuthProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}<Toaster/></body>
      </AuthProvider>
    </html>
  );
}
